### PR TITLE
Bma 26 create models bit of controllers

### PR DESCRIPTION
**Pull request by JamesMGithire**
Added seed data

### CODE REVIEW

**Comment by JamesMGithire** [comment]
Seeds are okay and previously commented out code has been uncommented

**Review by JamesMGithire — COMMENTED** [review]
Code is okay.

**Review by adamswonder — COMMENTED** [review]
Good code structure

**Review by adamswonder — COMMENTED** [review]
Validation well implemented

**Review by adamswonder — COMMENTED** [review]
Serializer looks okay!

**Comment by adamswonder** [comment]
The code follows good convention

**Pull request merged**
